name: find_my_ford
description: A tool for finding a new Ford vehicle.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  sleek_circular_slider: ^2.0.1
  carousel_slider: ^5.0.0
  intl: ^0.20.1
  align_positioned: ^5.0.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true