// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cejG2Ln9jcXSKyjDgAaHrzF5Y_XFkfo',
    appId: '1:571150062475:web:437eccc01c4f000665d58e',
    messagingSenderId: '571150062475',
    projectId: 'find-my-ford',
    authDomain: 'find-my-ford.firebaseapp.com',
    storageBucket: 'find-my-ford.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSi_kpE_typLYn_wRNOqnlfMptn-ZUW7I',
    appId: '1:571150062475:android:4e8b4db85a1d486d65d58e',
    messagingSenderId: '571150062475',
    projectId: 'find-my-ford',
    storageBucket: 'find-my-ford.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZiLI9BPE1yu7dYEdHpNf2iyoH2PJI_M',
    appId: '1:571150062475:ios:aa901fb4805003ed65d58e',
    messagingSenderId: '571150062475',
    projectId: 'find-my-ford',
    storageBucket: 'find-my-ford.firebasestorage.app',
    iosBundleId: 'com.example.findMyFord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZiLI9BPE1yu7dYEdHpNf2iyoH2PJI_M',
    appId: '1:571150062475:ios:aa901fb4805003ed65d58e',
    messagingSenderId: '571150062475',
    projectId: 'find-my-ford',
    storageBucket: 'find-my-ford.firebasestorage.app',
    iosBundleId: 'com.example.findMyFord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9cejG2Ln9jcXSKyjDgAaHrzF5Y_XFkfo',
    appId: '1:571150062475:web:fd633f5c601f43ea65d58e',
    messagingSenderId: '571150062475',
    projectId: 'find-my-ford',
    authDomain: 'find-my-ford.firebaseapp.com',
    storageBucket: 'find-my-ford.firebasestorage.app',
  );
}
